### ISSUE TITLE
Checking for a vm existing should treat a 404 as a valid response

### ISSUE THREAD

**Issue by idnorton** [Thermeon/terraform-provider-bigv#5]
Once a machine is known in the local state file, if it goes away upstream a 404 is returned.

Steps to reproduce:
1. Create a host via terraform (use distribution=none to reduce time taken)
2. Remove the host via the BigV control panel
3. Run terraform plan

The correct response is probably to refresh the cache to reflect reality.

**Comment by amorphic** [comment]
@idnorton any idea if this is still the case?

Also it's a bit weird having issues for another repo on our board. Can't use my beloved labels...:-(

**Comment by gbjk** [comment]
I don't think I've fixed this.

Regarding multiple repos: That's actually defacto: devops board primarily
unions puppet, but other boards I thought of as pure infra.

**Comment by gbjk** [comment]
Issue moved to [thermeon/devops #1045](https://github.com/thermeon/devops/issues/1045) via [**ZenHub**](https://www.zenhub.com/)
